### ISSUE TITLE
Merging ConstantInputs crashes on load

### ISSUE THREAD

**Issue by narukaze132** [palant/integrated-nodes-comfyui#5]
When I attempt to merge combos (e.g. sampler_name, scheduler) together in an integrated node, it attempts to access the 'type' attribute, which does not exist on ConstantInput objects, so the library promptly crashes and stops loading. (I may be mistaken on combo inputs being the cause, it may be integer inputs, but I'm presuming combos because they seem more "constant". Either way, it's crashing.)

**Comment by palant** [comment]
Are you using the latest version? #4 was fixed recently which sounds very similar.

Either way, could you copy the complete error message and stack trace please?

**Comment by narukaze132** [comment]
Yes, I am using the latest version. Here is the stack trace:

```
Traceback (most recent call last):
  File "D:\Programs\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Programs\ComfyUI\custom_nodes\integrated-nodes-comfyui\__init__.py", line 1, in <module>
    from .integrated_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS, WEB_DIRECTORY
  File "D:\Programs\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 649, in <module>
    load_config()
  File "D:\Programs\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 597, in load_config
    create_integrated_node(name, info)
  File "D:\Programs\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 561, in create_integrated_node
    merge_inputs(inputs, info.get("merge_inputs", {}))
  File "D:\Programs\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 496, in merge_inputs
    if target_input.type != source_input.type:
AttributeError: 'ConstantInput' object has no attribute 'type'
```

**Comment by palant** [comment]
Oh, you are both hiding and merging the same input? You should only do one.

The code needs to detect this scenario and to skip merging with an appropriate warning…

**Comment by palant** [comment]
Actually, maybe a better course of action is putting hiding after merging. This way multiple inputs could be merged into one and the resulting input hidden – assuming that it has a default value. Right now one would have to set an identical default value for all inputs that would otherwise be merged.

**Comment by palant** [comment]
I implemented a somewhat more extensive change after all. It made the logic simpler, so that this kind of issues should no longer happen regardless of ordering.
