### ISSUE TITLE
Internal Server Error - Cannot connect input of type {input} to output of type {output_type}

### ISSUE THREAD

**Issue by ghostsquad** [palant/integrated-nodes-comfyui#7]
![image](https://github.com/palant/integrated-nodes-comfyui/assets/903488/236206da-7a53-498d-bd74-0600b9b9fa0a)

```
KeyError: 'ClipSkip_2'
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 554, in create_integrated_node
    (processors, inputs, outputs, is_output_node) = process_workflow(workflow, export_outputs, rename_outputs)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 411, in process_workflow
    linked_inputs, dependencies = connect_links(nodes)
                                  ^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 396, in connect_links
    raise Exception(f"Cannot connect input of type {input} to output of type {output_type}")
Exception: Cannot connect input of type <integrated-nodes-comfyui.integrated_nodes.OptionalInput object at 0x000001B161E05310> to output of type INT
integrated_nodes.yaml: Ignoring integrated node ClipSkip_3, failed processing workflow
Error handling request
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\integrated-nodes-comfyui\integrated_nodes.py", line 643, in add_node
    GLOBAL_NODE_CLASS_MAPPINGS[actual_name] = NODE_CLASS_MAPPINGS[actual_name]
                                              ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
```

**Comment by palant** [comment]
If I see this correctly, Clip Skip is a Primitive node and Math Expression is a node from https://github.com/pythongosssss/ComfyUI-Custom-Scripts. Both nodes are implemented entirely on the client side, meaning that this limitation applies (from [Caveats](https://github.com/palant/integrated-nodes-comfyui#caveats) section):

> This is a purely server-side approach, it has no impact on special functionality added on the client side. This means that nodes like Primitive or Reroute cannot be integrated, these have no server-side equivalents.

So what you are trying to do cannot work. When using Create Integrated Node From Selection, client-side nodes are essentially ignored and only their result is kept. The expected result here is an integrated node consisting only of a CLIP Set Last Layer node with stop_at_clip_layer widget having -1 set as default value.

Still, I wonder how that exception happens, it’s a weird one. Could you post the `ClipSkip_3.json` file?
